In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu117


In [14]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
scalar.item()

7

In [18]:
vect = torch.tensor([6,6])
vect

tensor([6, 6])

In [20]:
vect.ndim

1

In [21]:
vect.shape

torch.Size([2])

In [23]:
matrx = torch.tensor([[7,8],
                      [9,10]])
matrx

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
matrx.ndim

2

In [25]:
matrx.shape

torch.Size([2, 2])

In [6]:
torch.cuda.is_available()

True

In [29]:
TENSOR = torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR2 = torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]],
                       [[10,20,30],
                       [20,30,40],
                       [30,40,50]]])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[10, 20, 30],
         [20, 30, 40],
         [30, 40, 50]]])

In [34]:
TENSOR2.ndim

3

In [35]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [36]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9993, 0.6793, 0.8996, 0.1996],
         [0.4285, 0.4937, 0.7451, 0.3499],
         [0.4369, 0.3904, 0.4049, 0.6973]]),
 torch.float32)

In [38]:
random_tensor_image = torch.rand(size=(224,224,3))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [42]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [44]:
ranges = torch.arange(0,10,1)
ranges

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ten_zeros = torch.zeros_like(ranges)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
ten_ones = torch.ones_like(ranges)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [48]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [49]:
some_tensor = torch.rand(3,4)
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")


Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


In [50]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [51]:
tensor * 10

tensor([10, 20, 30])

In [52]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [53]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.tensor([1,2,3]) * to