In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu117


In [14]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
scalar.item()

7

In [18]:
vect = torch.tensor([6,6])
vect

tensor([6, 6])

In [20]:
vect.ndim

1

In [21]:
vect.shape

torch.Size([2])

In [23]:
matrx = torch.tensor([[7,8],
                      [9,10]])
matrx

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
matrx.ndim

2

In [25]:
matrx.shape

torch.Size([2, 2])

In [6]:
torch.cuda.is_available()

True

In [29]:
TENSOR = torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR2 = torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]],
                       [[10,20,30],
                       [20,30,40],
                       [30,40,50]]])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [ 3,  4,  5]],

        [[10, 20, 30],
         [20, 30, 40],
         [30, 40, 50]]])

In [34]:
TENSOR2.ndim

3

In [35]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [36]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9993, 0.6793, 0.8996, 0.1996],
         [0.4285, 0.4937, 0.7451, 0.3499],
         [0.4369, 0.3904, 0.4049, 0.6973]]),
 torch.float32)

In [38]:
random_tensor_image = torch.rand(size=(224,224,3))
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [42]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [44]:
ranges = torch.arange(0,10,1)
ranges

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ten_zeros = torch.zeros_like(ranges)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
ten_ones = torch.ones_like(ranges)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [48]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [49]:
some_tensor = torch.rand(3,4)
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")


Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


In [50]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [51]:
tensor * 10

tensor([10, 20, 30])

In [52]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [53]:
tensor

tensor([1, 2, 3])

In [61]:
print(tensor * tensor)

tensor([1, 4, 9])


In [59]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [62]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [63]:
tensor @ tensor

tensor(14)

In [65]:
torch.matmul(tensor, tensor)

tensor(14)

In [66]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 936 µs, sys: 285 µs, total: 1.22 ms
Wall time: 712 µs


tensor(14)

In [67]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 252 µs, sys: 0 ns, total: 252 µs
Wall time: 171 µs


tensor(14)

In [68]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [69]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [70]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [71]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [72]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [73]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [74]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [78]:
tensor = torch.arange(10.,100.,10)
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [79]:
tensor.dtype

torch.float32

In [80]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [81]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [83]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [84]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [85]:
z = x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [86]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [89]:
y = torch.arange(1, 19).reshape(2, 3, 3)
y, y.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [90]:
print(f"First square bracket:\n{y[0]}") 
print(f"Second square bracket: {y[0][0]}") 
print(f"Third square bracket: {y[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [93]:
print(f"First square bracket:\n{y[1]}") 
print(f"Second square bracket: {y[0][1]}") 
print(f"Third square bracket: {y[0][2][1]}")

First square bracket:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
Second square bracket: tensor([4, 5, 6])
Third square bracket: 8


In [94]:
array = np.arange(1.,8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [95]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [96]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [97]:
tensor.dtype

torch.float32

In [98]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])

Tensor B:
tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [99]:
import random
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [100]:
import random
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [101]:
import torch
torch.cuda.is_available()

True

In [102]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [103]:
torch.cuda.device_count()

1

In [104]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [1]:
!nvidia-smi

Wed Aug  2 13:31:13 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 3000     Off  | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P8    15W /  N/A |    179MiB /  5934MiB |     27%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.cuda.device_count()

1

In [4]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [5]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [6]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [7]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')